"""Run with a local dev server: python tests/test_clubs.py (BASE_URL optional)."""
import os
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

URL = os.environ.get('BASE_URL', 'http://localhost:3001')
with sync_playwright() as p:
    executable = os.environ.get('CHROME_PATH')
    browser = p.chromium.launch(headless=True, **({'executable_path': executable} if executable else {}))
    context = browser.new_context()
    page = context.new_page()
    errors = []
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.goto(URL + '/login')
    page.wait_for_load_state('networkidle')
    print('Login controls:', [s.encode('ascii','replace').decode() for s in page.locator('button').all_text_contents()])
    page.locator('.preview-box select').select_option('Student')
    page.locator('.preview-box button').click()
    page.wait_for_url('**/dashboard')
    def nav(name):
        page.locator('.side-nav').get_by_role('button',name=name,exact=True).click()
    def open_club(name):
        page.get_by_role('button',name='Open '+name,exact=False).click()
        expect(page.get_by_role('heading',name=name,exact=True)).to_be_visible()
    def role(name):
        page.locator('.role-switch select').select_option(name)
        expect(page.get_by_role('switch')).to_be_enabled()
    def private(hidden=True):
        expect(page.get_by_role('region',name='Club events')).to_have_count(0 if hidden else 1)
        expect(page.get_by_role('region',name='Club announcements')).to_have_count(0 if hidden else 1)
        expect(page.get_by_role('region',name='Club members')).to_have_count(0 if hidden else 1)
    nav('Discover clubs')
    page.wait_for_load_state('networkidle')
    expect(page.locator('.clubs-workspace .club-card')).to_have_count(24)
    page.get_by_role('textbox',name='Search clubs').fill('IEEE')
    expect(page.locator('.clubs-workspace .club-card')).to_have_count(1)
    open_club('IEEE')
    private()
    page.get_by_role('button',name='Request to join',exact=True).click()
    expect(page.get_by_text('Request pending',exact=True)).to_be_visible()
    private()
    page.reload()
    expect(page.get_by_text('Request pending',exact=True)).to_be_visible()
    private()
    print('PASS: 24 clubs, search, public page, pending request, reload restriction')
    nav('My Clubs')
    expect(page.locator('.clubs-workspace .club-card')).to_have_count(0)
    expect(page.get_by_role('button',name='IEEE · Pending')).to_be_visible()
    nav('Discover clubs'); open_club('Coding')
    page.get_by_role('button',name='Request to join',exact=True).click()
    page.get_by_role('switch').check()
    private(False)
    nav('My Clubs')
    expect(page.locator('.clubs-workspace .club-card')).to_have_count(2)
    open_club('IEEE'); private(False)
    page.get_by_role('button',name='RSVP',exact=True).first.click()
    expect(page.get_by_role('button',name='Cancel RSVP',exact=True)).to_be_visible()
    page.reload()
    expect(page.get_by_role('button',name='Cancel RSVP',exact=True)).to_be_visible()
    page.get_by_role('button',name='Cancel RSVP',exact=True).click()
    expect(page.get_by_role('button',name='RSVP',exact=True).first).to_be_visible()
    page.get_by_role('button',name='RSVP',exact=True).first.click()
    expect(page.get_by_role('region',name='Club members')).to_contain_text('Aarav Sharma')
    expect(page.get_by_role('region',name='Club announcements')).to_contain_text('breadboard')
    print('PASS: batch auto-accept, My Clubs, members, announcements, RSVP/cancel/persistence')
    nav('Discover clubs'); open_club('Singing')
    page.get_by_role('button',name='Request to join',exact=True).click(); private(False)
    page.get_by_role('button',name='Leave club',exact=True).click(); private()
    nav('My Clubs'); expect(page.locator('.clubs-workspace .club-card')).to_have_count(2)
    page.get_by_role('switch').uncheck()
    nav('Discover clubs'); open_club('Robotics')
    page.get_by_role('button',name='Request to join',exact=True).click(); private()
    role('Faculty')
    expect(page.get_by_role('button',name='Approve',exact=True)).to_be_visible()
    page.get_by_role('button',name='Reject',exact=True).click()
    expect(page.get_by_text('No pending requests.')).to_be_visible()
    role('Student')
    expect(page.get_by_text('Request rejected — you can apply again.')).to_be_visible()
    private()
    page.get_by_role('button',name='Request again',exact=True).click()
    role('Faculty')
    page.get_by_role('button',name='Approve',exact=True).click()
    page.get_by_label('Request type',exact=True).select_option('announcement')
    page.get_by_label('Request title',exact=True).fill('Robotics team update')
    page.get_by_label('Purpose and details',exact=True).fill('Bring your new prototype on Friday.')
    page.get_by_role('button',name='Submit request',exact=True).click()
    page.get_by_role('article',name='Robotics team update',exact=True).get_by_role('button',name='Approve request',exact=True).click()
    expect(page.get_by_role('region',name='Club announcements').get_by_role('heading',name='Robotics team update')).to_be_visible()
    role('Student'); private(False)
    expect(page.get_by_text('Bring your new prototype on Friday.')).to_be_visible()
    print('PASS: instant acceptance, leave, manual rejection/reapply/approval, admin publishing')
    nav('Discover clubs'); open_club('Drama')
    page.get_by_role('button',name='Request to join',exact=True).click()
    role('Faculty'); private()
    expect(page.get_by_role('button',name='Approve',exact=True)).to_have_count(0)
    role('Admin'); page.get_by_role('button',name='Approve',exact=True).click()
    role('Student'); private(False)
    nav('Discover clubs'); open_club('Dancing')
    page.get_by_role('button',name='Request to join',exact=True).click()
    page.get_by_role('button',name='Cancel request',exact=True).click()
    expect(page.get_by_role('button',name='Request to join',exact=True)).to_be_visible()
    nav('My Clubs'); open_club('IEEE')
    page.get_by_role('button',name='Leave club',exact=True).click(); private()
    page.reload(); private()
    page.get_by_role('switch').check()
    page.get_by_role('button',name='Request to join',exact=True).click()
    expect(page.get_by_role('button',name='RSVP',exact=True).first).to_be_visible()
    expect(page.get_by_role('button',name='Cancel RSVP',exact=True)).to_have_count(0)
    nav('My Clubs'); open_club('Coding')
    expect(page.get_by_role('region',name='Club announcements')).not_to_contain_text('Robotics team update')
    print('PASS: club-admin scope, campus-admin approval, cancellation, leaving clears RSVP, club isolation')
    # Enable auto-accept and visit every club, checking that its own content is present.
    all_club_names = [
        'IEEE', 'Coding', 'Robotics', 'AI & Data Science', 'Aerospace & Rocketry', 'Cybersecurity',
        'Photography', 'Design Society', 'Film Society', 'Fine Arts', 'Literary Society', 'Fashion & Apparel',
        'Singing', 'Dancing', 'Drama', 'Music Band', 'Culinary Arts', 'Philosophy',
        'Debate', 'Green Collective', 'E-Cell', 'Model UN & Diplomacy', 'Social Impact', 'Mind & Wellness'
    ]
    for name in all_club_names:
        nav('Discover clubs'); open_club(name)
        request = page.get_by_role('button',name='Request to join',exact=True)
        if request.count(): request.click()
        private(False)
        expect(page.get_by_role('region',name='Club events').locator('article').first).to_be_visible()
        expect(page.get_by_role('region',name='Club announcements')).to_contain_text('Welcome to '+name)
    nav('My Clubs'); expect(page.locator('.clubs-workspace .club-card')).to_have_count(24)
    page.set_viewport_size({'width':390,'height':844})
    open_club('Photography')
    expect(page.get_by_role('button',name='RSVP',exact=True).first).to_be_visible()
    assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'Mobile overflow'
    page.evaluate("window.scrollTo({top: 0, behavior: 'instant'})")
    page.screenshot(path=str(Path(os.environ.get('TEMP','.'))/'campus-clubs-mobile.png'),full_page=True)
    assert not errors, errors
    print('PASS: all twenty-four club pages, mobile layout, no browser errors')
    browser.close()
