"""Role-by-role governance E2E. Requires local server and Python Playwright."""
import os
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
URL=os.environ.get('BASE_URL','http://localhost:3001')
with sync_playwright() as p:
    binary=os.environ.get('CHROME_PATH')
    browser=p.chromium.launch(headless=True,**({'executable_path':binary} if binary else {}))
    page=browser.new_page(viewport={'width':1440,'height':1000})
    errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto(URL+'/login');page.wait_for_load_state('networkidle')
    page.locator('.preview-box select').select_option('Club Leader')
    page.locator('.preview-box button').click();page.wait_for_url('**/dashboard')
    def nav(name):page.locator('.side-nav').get_by_role('button',name=name,exact=False).click()
    def role(value):
        page.locator('.role-switch select').select_option(value)
        expect(page.get_by_role('switch')).to_be_enabled()
    def account(value):page.get_by_label('Club / account',exact=True).select_option(value)
    def card(title):return page.get_by_role('article',name=title,exact=True)
    def propose(kind,title,amount=None):
        page.get_by_label('Request type',exact=True).select_option(kind)
        page.get_by_label('Request title',exact=True).fill(title)
        page.get_by_label('Purpose and details',exact=True).fill('Details for '+title)
        if amount:page.get_by_label('Amount (₹)',exact=True).fill(amount)
        if kind=='event':
            page.get_by_label('Event date and time',exact=True).fill('2026-11-20T16:00')
            page.get_by_label('Event venue',exact=True).fill('IEEE Laboratory')
        page.get_by_role('button',name='Submit request',exact=True).click()
        expect(card(title)).to_be_visible()
    nav('Finance');account('ieee')
    expect(page.get_by_test_id('account-balance')).to_have_text('₹0.00')
    propose('funding','Sensors funding','5000')
    expect(card('Sensors funding')).to_contain_text('Awaiting faculty')
    expect(card('Sensors funding').get_by_role('button',name='Approve request')).to_have_count(0)
    page.get_by_role('switch').check()
    expect(card('Sensors funding')).to_contain_text('Awaiting faculty')
    print('PASS: leader proposal requires faculty; membership auto-accept does not bypass finance')
    role('Student Council');account('ieee')
    expect(card('Sensors funding').get_by_role('button',name='Release funding')).to_have_count(0)
    expect(page.get_by_role('button',name='Submit request',exact=True)).to_have_count(0)
    role('Faculty');account('ieee')
    card('Sensors funding').get_by_label('Review note / rejection reason').fill('Faculty recommends equipment grant')
    card('Sensors funding').get_by_role('button',name='Approve request',exact=True).click()
    expect(card('Sensors funding')).to_contain_text('Awaiting Admin authorization')
    role('Admin');account('ieee')
    card('Sensors funding').get_by_role('button',name='Authorize funding',exact=True).click()
    expect(card('Sensors funding')).to_contain_text('Awaiting Student Council release')
    expect(page.get_by_test_id('account-balance')).to_have_text('₹0.00')
    expect(card('Sensors funding').get_by_role('button',name='Release funding')).to_have_count(0)
    role('Student Council');account('ieee')
    card('Sensors funding').get_by_role('button',name='Release funding',exact=True).click()
    expect(card('Sensors funding')).to_contain_text('Completed')
    expect(card('Sensors funding').get_by_role('button',name='Release funding')).to_have_count(0)
    expect(page.get_by_test_id('account-balance')).to_have_text('₹5,000.00')
    account('council');expect(page.get_by_test_id('account-balance')).to_have_text('₹2,45,000.00')
    page.get_by_label('Receipt reference',exact=True).fill('Receipt-001')
    page.get_by_label('Receipt amount (₹)',exact=True).fill('100.25')
    page.get_by_role('button',name='Record receipt',exact=True).click()
    expect(page.get_by_test_id('account-balance')).to_have_text('₹2,45,100.25')
    print('PASS: faculty > Admin > Council release, separate treasury debit/club credit, receipt precision')
    role('Club Leader');account('ieee')
    propose('expense','Sensors expense','1250.25')
    role('Faculty');account('ieee')
    card('Sensors expense').get_by_role('button',name='Approve request',exact=True).click()
    expect(page.get_by_test_id('account-balance')).to_have_text('₹3,749.75')
    account('coding');expect(page.get_by_test_id('account-balance')).to_have_text('₹0.00')
    role('Club Leader');account('ieee')
    propose('expense','Too expensive','99999')
    role('Faculty');account('ieee')
    card('Too expensive').get_by_role('button',name='Approve request',exact=True).click()
    expect(page.locator('.club-error')).to_contain_text('insufficient funds')
    expect(card('Too expensive')).to_contain_text('Awaiting faculty')
    expect(card('Too expensive').get_by_role('button',name='Reject request',exact=True)).to_be_disabled()
    card('Too expensive').get_by_label('Review note / rejection reason').fill('Outside available club budget')
    card('Too expensive').get_by_role('button',name='Reject request',exact=True).click()
    expect(card('Too expensive')).to_contain_text('Rejected')
    role('Club Leader');account('ieee')
    propose('funding','Cancelled proposal','50')
    card('Cancelled proposal').get_by_role('button',name='Cancel request',exact=True).click()
    expect(card('Cancelled proposal')).to_contain_text('Cancelled')
    propose('event','Faculty reviewed event')
    propose('announcement','Faculty reviewed notice')
    propose('activity','Volunteer setup checklist')
    role('Faculty');account('ieee')
    for title in ['Faculty reviewed event','Faculty reviewed notice','Volunteer setup checklist']:
        card(title).get_by_role('button',name='Approve request',exact=True).click()
        expect(card(title)).to_contain_text('Completed')
    print('PASS: isolated club expenses, overdraw rejection, reason required, cancellation, operation approvals')
    role('Student')
    nav('Discover clubs');page.get_by_role('button',name='Open IEEE',exact=False).click()
    page.get_by_role('button',name='Request to join',exact=True).click()
    expect(page.get_by_role('region',name='Club events')).to_contain_text('Faculty reviewed event')
    expect(page.get_by_role('region',name='Club announcements')).to_contain_text('Faculty reviewed notice')
    expect(page.get_by_role('region',name='Approved club activities')).to_contain_text('Volunteer setup checklist')
    page.get_by_role('region',name='Club events').get_by_role('article').filter(has=page.get_by_role('heading',name='Faculty reviewed event')).get_by_role('button',name='RSVP',exact=True).click()
    expect(page.get_by_role('button',name='Cancel RSVP')).to_have_count(1)
    # Membership review by a leader also needs faculty approval.
    page.get_by_role('button',name='Leave club',exact=True).click()
    page.get_by_role('switch').uncheck()
    page.get_by_role('button',name='Request to join',exact=True).click()
    role('Club Leader')
    page.get_by_role('button',name='Recommend approval',exact=True).click()
    expect(page.get_by_role('region',name='Join requests')).to_contain_text('Aarav')
    role('Faculty')
    recommendation=page.get_by_role('article',name='Approve membership: Aarav Sharma · Student',exact=True)
    recommendation.get_by_role('button',name='Approve request',exact=True).click()
    role('Student')
    expect(page.get_by_role('region',name='Club events')).to_be_visible()
    print('PASS: approved operations visible to member, new event RSVP, leader membership decision requires faculty')
    role('Admin');nav('Finance');account('singing')
    page.get_by_label('Staff profile',exact=True).select_option('preview:Faculty')
    page.get_by_role('button',name='Assign to club',exact=True).click()
    role('Faculty');account('singing')
    propose('funding','Singing grant','100')
    expect(card('Singing grant')).to_contain_text('Awaiting Admin authorization')
    role('Admin');account('singing')
    card('Singing grant').get_by_label('Review note / rejection reason').fill('Resubmit next term')
    card('Singing grant').get_by_role('button',name='Reject request',exact=True).click()
    page.get_by_role('button',name='Remove assignment',exact=True).click()
    role('Faculty')
    assert 'Singing' not in page.get_by_label('Club / account',exact=True).inner_text()
    role('Admin');account('ieee')
    card('Sensors funding').get_by_text('Approval history (4)',exact=True).click()
    expect(card('Sensors funding')).to_contain_text('Faculty recommends equipment grant')
    page.reload();nav('Finance');account('ieee')
    expect(page.get_by_test_id('account-balance')).to_have_text('₹3,749.75')
    page.set_viewport_size({'width':390,'height':844})
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth'), 'mobile overflow'
    page.evaluate("window.scrollTo({top:0,behavior:'instant'})")
    page.screenshot(path=str(Path(os.environ.get('TEMP','.'))/'campus-governance.png'),full_page=True)
    assert not errors,errors
    print('PASS: Admin assigns/revokes faculty scope, Admin rejection, audit trail, persistence and mobile layout')
    browser.close()
